name: worker_location_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.61.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  get: ^4.6.5
  pausable_timer: ^1.0.0+7
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
   - lib/assets/
     

  