// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpPZM8gt05c1WH116qbWw8QVBvsK7IsQ',
    appId: '1:1028809053483:web:9972cba15ec40e80b3616e',
    messagingSenderId: '1028809053483',
    projectId: 'workerlocationsystem',
    authDomain: 'workerlocationsystem.firebaseapp.com',
    storageBucket: 'workerlocationsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANHqOYzq3yZc3XBqMy56onWRPg2U22wBA',
    appId: '1:1028809053483:android:cc5f9eb198c86894b3616e',
    messagingSenderId: '1028809053483',
    projectId: 'workerlocationsystem',
    storageBucket: 'workerlocationsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU16CP18KlO6LmxvNZhHXZl6Y1qBXnFx4',
    appId: '1:1028809053483:ios:8e8ae0de70a40aa5b3616e',
    messagingSenderId: '1028809053483',
    projectId: 'workerlocationsystem',
    storageBucket: 'workerlocationsystem.appspot.com',
    iosClientId: '1028809053483-28d3dkuc6scdqqu3blilfgmf699aoep5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesiLast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU16CP18KlO6LmxvNZhHXZl6Y1qBXnFx4',
    appId: '1:1028809053483:ios:8e8ae0de70a40aa5b3616e',
    messagingSenderId: '1028809053483',
    projectId: 'workerlocationsystem',
    storageBucket: 'workerlocationsystem.appspot.com',
    iosClientId: '1028809053483-28d3dkuc6scdqqu3blilfgmf699aoep5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesiLast',
  );
}
